### ISSUE TITLE
Bug: import TradingEnvironment throws SyntaxError in Jupyter tutorial

### ISSUE THREAD

**Issue by cer-nagas** [notadamking/tensortrade#28] opened 2019-10-06 22:33 UTC
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/tensortrader) or [on the TensorTrade Gitter channel]((https://gitter.im/tensortrade-framework/community/) instead of opening a GitHub issue.</em>

**System information**

- Have I written custom code (as opposed to using example directory):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorTrade version: 0.0.1a11
- TensorFlow version: 1.13.1
- Python version: 3.5.5
- CUDA/cuDNN version:
- GPU model and memory:

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

Running [In: 3]
Got `File "my-environment/lib/python3.5/site-packages/tensortrade/environments/trading_environment.py", line 169
    reward: float = self._reward_strategy.get_reward(
          ^
SyntaxError: invalid syntax`

**Describe the expected behavior**

Running without error

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
From file TensorTrade_Tutorial.ipynb

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by dahifi** [comment] 2019-10-18 22:11
I'm getting the same running off of the Docker build in Juptyter" 

```
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-5-9af93dc25d4b>", line 1, in <module>
    from tensortrade.environments import TradingEnvironment

  File "/tensortrade/__init__.py", line 2, in <module>
    from . import environments

  File "/tensortrade/environments/__init__.py", line 1, in <module>
    from .trading_environment import TradingEnvironment

  File "/tensortrade/environments/trading_environment.py", line 19, in <module>
    import tensortrade.exchanges as exchanges

  File "/tensortrade/exchanges/__init__.py", line 6, in <module>
    from .instrument_exchange import InstrumentExchange

  File "/tensortrade/exchanges/instrument_exchange.py", line 23, in <module>
    from tensortrade.features import FeaturePipeline

  File "/tensortrade/features/__init__.py", line 1, in <module>
    from .feature_pipeline import FeaturePipeline

  File "/tensortrade/features/feature_pipeline.py", line 36
    self._dtype: DTypeString = kwargs.get('dtype', np.float16)
               ^
SyntaxError: invalid syntax
```

**Comment by dahifi** [comment] 2019-10-19 02:05
Looks like @notadamking is using Python >= 3.6. Variable annotations were released in it and I think this is responsible for the error I'm seeing. Updating the Dockerfile to pull Python 3.6 should do the trick. 

Will confirm.

**Comment by dahifi** [comment] 2019-10-19 03:08
Confirmed. Recommend bumping minimum Python version in the docs to 3.6 unless we want to go back and refactor out these syntax errors.

**Comment by notadamking** [comment] 2019-10-20 18:48
Is this still happening?

**Closed** 2019-10-29 01:09 UTC
Labels: bug, documentation
